export const PROXY_ENABLE_KEY = "REVERSE_PROXY_ENABLE";
export const PROXY_TYPE_KEY = "REVERSE_PROXY";
export const SERVEO_SUBDOMAIN_KEY = "SERVEO_SUBDOMAIN";
export const NGROK_TOKEN_KEY = "NGROK_AUTHTOKEN";
export const NGROK_SUBDOMAIN_KEY = "NGROK_SUBDOMAIN";
export const LOCALTUNNEL_SUBDOMAIN_KEY = "LOCALTUNNEL_SUBDOMAIN";
export const LOCALTUNNEL_AUTO_CONFIRM_KEY = "LOCALTUNNEL_AUTO_CONFIRM";
